{% set name = "ndx-pose" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndx-pose-{{ version }}.tar.gz
  sha256: 167dc25f13ba1abc924543cbe44123703303b3f61e5baf6108334a3fe6def11c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pynwb >=1.5.0,<3
    - hdmf >=2.5.6,<4

test:
  imports:
    - ndx_pose
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rly/ndx-pose
  summary: NWB extension to store pose estimation data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rly
