{% set name = "ndx-pose" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ndx_pose-{{ version }}.tar.gz
  sha256: 69a9a139363ccf8406f36752146d345914330e69921b9734db2425fc9808a0a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - pynwb >=2.6.0
    - hdmf >=3.13.0

test:
  source_files:
    - src/pynwb/tests
    - examples
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - ndx_pose
  commands:
    - pip check
    - pytest -vv

about:
  home: https://github.com/rly/ndx-pose
  summary: NWB extension to store pose estimation data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rly
