{% set name = "ndx-pose" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndx_pose-{{ version }}.tar.gz
  sha256: d6e8f99274e579fe13b2ae43ec78a0685addff2ff4be538343a33871d4a331f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - pynwb >=2.6.0
    - hdmf >=3.13.0

test:
  requires:
    - pip
    - pytest
  imports:
    - ndx_pose
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/rly/ndx-pose
  summary: NWB extension to store pose estimation data
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rly
